// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: user_followers.sql

package db

import (
	"context"
)

const createFollower = `-- name: CreateFollower :one
INSERT INTO user_followers (
  follower_id,
  followee_id
) VALUES (
  $1, $2
) RETURNING follower_id, followee_id
`

type CreateFollowerParams struct {
	FollowerID string `json:"follower_id"`
	FolloweeID string `json:"followee_id"`
}

func (q *Queries) CreateFollower(ctx context.Context, arg CreateFollowerParams) (UserFollower, error) {
	row := q.db.QueryRowContext(ctx, createFollower, arg.FollowerID, arg.FolloweeID)
	var i UserFollower
	err := row.Scan(&i.FollowerID, &i.FolloweeID)
	return i, err
}

const deleteFollower = `-- name: DeleteFollower :exec
DELETE FROM user_followers
WHERE follower_id = $1
`

func (q *Queries) DeleteFollower(ctx context.Context, followerID string) error {
	_, err := q.db.ExecContext(ctx, deleteFollower, followerID)
	return err
}

const getFollowee = `-- name: GetFollowee :one
SELECT follower_id, followee_id FROM user_followers
WHERE follower_id = $1 LIMIT 1
`

func (q *Queries) GetFollowee(ctx context.Context, followerID string) (UserFollower, error) {
	row := q.db.QueryRowContext(ctx, getFollowee, followerID)
	var i UserFollower
	err := row.Scan(&i.FollowerID, &i.FolloweeID)
	return i, err
}

const getFollower = `-- name: GetFollower :one
SELECT follower_id, followee_id FROM user_followers
WHERE followee_id = $1 LIMIT 1
`

func (q *Queries) GetFollower(ctx context.Context, followeeID string) (UserFollower, error) {
	row := q.db.QueryRowContext(ctx, getFollower, followeeID)
	var i UserFollower
	err := row.Scan(&i.FollowerID, &i.FolloweeID)
	return i, err
}

const listFollowees = `-- name: ListFollowees :many
SELECT follower_id, followee_id FROM user_followers
ORDER BY follower_id
LIMIT $1
OFFSET $2
`

type ListFolloweesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFollowees(ctx context.Context, arg ListFolloweesParams) ([]UserFollower, error) {
	rows, err := q.db.QueryContext(ctx, listFollowees, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFollower{}
	for rows.Next() {
		var i UserFollower
		if err := rows.Scan(&i.FollowerID, &i.FolloweeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT follower_id, followee_id FROM user_followers
ORDER BY followee_id
LIMIT $1
OFFSET $2
`

type ListFollowersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]UserFollower, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFollower{}
	for rows.Next() {
		var i UserFollower
		if err := rows.Scan(&i.FollowerID, &i.FolloweeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
